community/urls.py
from django.urls import path
from community import views

app_name = 'community'

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:article_id>/", views.article_detail, name="article_detail"),
    path("<int:article_id>/update_article/", views.update_article, name="update_article"),
    path("<int:article_id>/delete_article/", views.delete_article, name="delete_article"),
    path("<int:article_id>/create_comment/", views.create_comment, name="create_comment"),
    path("<int:article_id>/delete_comment/<int:comment_id>/", views.delete_comment, name="delete_comment"),
    path("create_article/", views.create_article, name="create_article"),
]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include("users.urls")),
    path("community/", include("community.urls")),
]

users/urls.py
from django.urls import path
from users import views

app_name = 'users'

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("user/", views.user, name="user"),
    path("<str:username>/", views.profile, name="profile"),
]

community/models.py
from django.db import models
from users.models import User

# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        return str(self.title)


class Comment(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    # comment = Comment.objects.get(id=id)
    # comment.user
    # comment.article

    # user = request.user
    # user.article_set.all
    # user.comment_set.all
    def __str__(self):
        return str(f'{self.user}님이 작성하신 {self.content}')

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.
class User(AbstractUser):
    profile = models.TextField(max_length=500, blank=True)
    nickname = models.CharField(max_length=20, blank=True)

community/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from community.models import Article, Comment
from django.shortcuts import get_object_or_404
from django.db.models import Count

# Create your views here.

def index(request):
    # articles = Article.objects.all().order_by('-created_at')
    articles = Article.objects.annotate(num_comments=Count('comment'))
    context={
        "articles":articles
    }

    return render(request, "index.html", context)


def create_article(request):
    if request.method == "GET":
        return render(request, "create_article.html")
    elif request.method == "POST":
        # input name=title 기훈님안녕하세요
        title = request.POST.get("title")
        # print(title) -> 기훈님안녕하세요
        content = request.POST.get("content")
        user = request.user
        Article.objects.create(title=title, content=content, user = user)
        return redirect("community:index")

def article_detail(request, article_id):
    if request.method == 'GET':
        article = Article.objects.get(id=article_id)
        # article = get_object_or_404(Article, id=article_id)
        context = {
            "article":article
        }
        return render(request, "article_detail.html", context)


def update_article(request, article_id):
    article = Article.objects.get(id=article_id)
    if request.user != article.user:
        return HttpResponse("권한이 없습니다.")

    if request.method == 'GET':
        context = {
        "article":article
        }
        return render(request, "update_article.html", context)

    elif request.method == 'POST':
        article.title = request.POST.get("title")
        article.content = request.POST.get("content")
        article.save()
        return redirect("community:article_detail", article_id)



def delete_article(request, article_id):
    if request.method == 'POST':
        article = Article.objects.get(id=article_id)
        if request.user != article.user:
            return HttpResponse("권한이 없습니다.")
        article.delete()
        return redirect("community:index")

def create_comment(request, article_id):
    if request.method == 'POST':
        content = request.POST.get("content")
        user = request.user
        Comment.objects.create(content=content, user = user, article_id= article_id)
        return redirect("community:article_detail", article_id)


def delete_comment(request, article_id, comment_id):
    if request.method == 'POST':
        comment = Comment.objects.get(id=comment_id)
        if comment.user == request.user:
            comment.delete()
            return redirect("community:article_detail", article_id)
        else:
            return HttpResponse("권한이 없습니다!")

users/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from .models import User
from django.contrib.auth import authenticate, login as loginsession, password_validation
from django.shortcuts import get_object_or_404

# Create your views here.



def signup(request):
    if request.method == "GET":
        return render(request, 'signup.html')
    elif request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        passwordcheck = request.POST.get('passwordcheck')
        if password == passwordcheck:
            # password_valid = password_validation.validate_password(password)
            User.objects.create_user(username=username, password=password)
            return HttpResponse("회원가입 완료!")
        else:
            # 안좋은 코드
            return HttpResponse("비밀번호 확인 틀렸습니다")
    else:
        # 좋은 코드 아님.
        return HttpResponse("허용되지 않은 메소드입니다.")


def login(request):
    if request.method == "GET":
        return render(request, 'login.html')
    elif request.method == "POST":

        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)
        if user is not None:
            loginsession(request, user)
            return redirect('users:user')
        else:
            return HttpResponse("로그인 실패")

def user(request):
    return HttpResponse(request.user)

def profile(request, username):
    user = get_object_or_404(User, username=username)
    context = {
        "user": user,
    }
    return render(request, 'profile.html', context)

community/templates/article_detail.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Article detail</title>
  </head>
  <body>
    <h1>{{ article.title }}</h1>
    <p>{{ article.content}}</p>
    <p>{{ article.created_at }}</p>
    <p>{{ article.user }}</p>

    {% if article.user == request.user %}
    <a href="{% url 'community:update_article' article.id %}">
      <button>수정버튼</button>
    </a>

    <form
      action="{% url 'community:delete_article' article.id %}"
      method="POST"
    >
      {% csrf_token %}
      <button type="submit">삭제버튼</button>
    </form>

    {% endif %}

    <div>
      <h3>댓글 부분</h3>
      {% for comment in article.comment_set.all %}
      <div>
        <div>댓글 작성자 : {{ comment.user }}</div>
        <div>댓글 내용 : {{ comment.content }}</div>
        {% if comment.user == request.user %}
        <form
          action="{% url 'community:delete_comment' article.id comment.id %}"
          method="post"
        >
          {% csrf_token %}
          <input type="submit" />
        </form>
        {% endif %}
        <br />
      </div>
      {% endfor %}
    </div>

    <div>
      <form
        action="{% url 'community:create_comment' article.id %}"
        method="post"
      >
        {% csrf_token %}
        <input
          type="text"
          name="content"
          id="content"
          placeholder="댓글 입력해주세요!"
        />
        <input type="submit" />
      </form>
    </div>
  </body>
</html>

community/templates/create_article.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>게시글 작성 페이지</title>
  </head>
  <body>
    <h1>게시글 작성페이지입니다.</h1>
    <form action="{% url 'community:create_article' %}" method="POST">
      {% csrf_token %}
      <div>
        <input type="text" name="title" id="title" placeholder="title" />
      </div>
      <div>
        <textarea
          name="content"
          id="content"
          cols="30"
          rows="10"
          placeholder="내용"
        ></textarea>
      </div>
      <input type="submit" />
    </form>
  </body>
</html>

community/templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>인덱스 페이지</title>
  </head>
  <body>
    <h1>모든 게시글들</h1>
    {% for article in articles %}
    <div>
      <a href="{% url 'community:article_detail' article.pk %}">
        <h3>{{ article.title }}</h3></a
      >

      <div>카운트 쓴 방법 : {{ article.comment_set.all.count }}</div>
      <div>두번째 방법 : {{ article.num_comments }}</div>
    </div>
    {% endfor %}
  </body>
</html>

community/templates/update_article.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>게시글 수정 페이지</title>
  </head>
  <body>
    <h1>게시글 수정페이지입니다.</h1>
    <form
      action="{% url 'community:update_article' article.id %}"
      method="POST"
    >
      {% csrf_token %}
      <div>
        <input
          type="text"
          name="title"
          id="title"
          placeholder="title"
          value="{{ article.title }}"
        />
      </div>
      <div>
        <textarea
          name="content"
          id="content"
          cols="30"
          rows="10"
          placeholder="내용"
        >
        {{ article.content }}
    
    </textarea
        >
      </div>
      <input type="submit" />
    </form>
  </body>
</html>

users/templates/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>로그인</title>
  </head>
  <body>
    <h1>로그인 페이지</h1>

    <form action="{% url 'users:login' %}" method="POST">
      {% csrf_token %}
      <input
        type="text"
        name="username"
        placeholder="username"
        id="username"
        class="username"
      />
      <input type="password" name="password" placeholder="password" />
      <input type="submit" />
    </form>
  </body>
</html>

users/templates/profile.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>프로필 페이지입니다.</title>
  </head>
  <body>
    <div>{{ user }}님의 페이지이고 마지막 로그인은 {{ user.last_login }}</div>
    <div>지금 로그인한 사용자는 {{ request.user }}</div>

    <h2>작성한 글</h2>
    <div>
      {% for article in user.article_set.all %}

      <div>{{ article.title }}</div>
      <div>{{ article.content }}</div>
      {% endfor %}
    </div>

    {% if user == request.user %}
    <div>내 프로필 페이지</div>
    <button>프로필 편집버튼</button>
    {% endif %}
  </body>
</html>

users/templates/signup.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Sign up</title>
  </head>
  <body>
    <h1>회원가입 페이지</h1>

    <form action="{% url 'users:signup' %}" method="POST">
      {% csrf_token %}
      <input
        type="text"
        name="username"
        placeholder="username"
        id="username"
        class="username"
      />

      <input type="password" name="password" placeholder="password" />
      <input type="password" name="passwordcheck" placeholder="passwordcheck" />
      <input type="submit" />
    </form>
  </body>
</html>